---
- name: pin defaults
  set_fact: "{{item.key}}={{item.value}}"
  with_dict:
    openwrt_ssh: "{{openwrt_ssh}}"
    openwrt_scp: "{{openwrt_scp}}"
    openwrt_ssh_user: "{{openwrt_ssh_user}}"
    openwrt_ssh_host: "{{openwrt_ssh_host}}"
    openwrt_user_host: "{{openwrt_ssh_user|quote}}@{{openwrt_ssh_host|quote}}"
  tags: always

- name: install recommended packages
  include: packages.yml
  when: openwrt_install_recommended_packages
