---
- name: "check for command {{ item.key }}"
  command: "which {{ item.key|quote }}"
  register: _package
  check_mode: false
  changed_when: false
  failed_when: false

- name: "install {{ item.value }} to provide {{ item.key }}"
  opkg:
    name: "{{ item.value }}"
  when: _package.rc
